{% set name = "asgi-csrf" %}
{% set version = "0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6e9d3bddaeac1a8fd33b188fe2abc8271f9085ab7be6e1a7f4d3c9df5d7f741a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - itsdangerous
    - python >=3.6
    - python-multipart

test:
  imports:
    - asgi_csrf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/simonw/asgi-csrf
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: ASGI middleware for protecting against CSRF attacks
  description: |
    This middleware implements the Double Submit Cookie pattern, where a cookie
     is set that is then compared to a csrftoken hidden form field or a
     x-csrftoken HTTP header.

extra:
  recipe-maintainers:
    - thewchan
